config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :tweets, except: [:edit, :update] do
    resources :comments, only: [:create, :destroy]
    member do
      post :retweet
    end
  end

  resources :profiles do
    collection do
      post 'follow/:id' => :follow, as: 'follow'
      post 'unfollow/:id' => :unfollow, as: 'unfollow'
    end
  end

  resources :likes, only: :create

  devise_for :users
  root to: "tweets#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = User.find(params[:id])
  end

  def follow
    @profile = User.find(params[:id])
    follow_body = { "follower_id" => current_user.id, "followee_id" => @profile.id }
    @follow = Follow.new(follow_body)

    respond_to do |format|
      if @follow.save
        format.turbo_stream
      else
        format.html { redirect_back fallback_location: @profile, alert: "Could not follow" }
      end
    end
  end

  def unfollow
    @profile = User.find(params[:id])
    follower_id = @profile.followers.find(current_user.id)

    @follow = Follow.find_by follower_id: follower_id

    @follow.destroy
  end
end

app/views/profiles/show.html.erb
<div class="p-6">
  <div class="flex items-center justify-between space-x-4">
    <div class="flex items-center">
      <%= profile_image(@profile, size: "large") %>
    </div>
    <div class="flex-1">
      <div>
        <h1 class="font-bold text-3xl"><%= @profile.name %></h1>
        <%= "@" + @profile.username %>
      </div>
    </div>
    <div>
      <% if @profile.id == current_user.id %>
        <%= link_to "Edit profile",  edit_user_registration_path, class: "inline-flex justify-center items-center px-5 py-2 rounded-full border ring-4 focus:ring-sky-50 ring-transparent hover:ring-sky-50 hover:border-gray-300" if current_user %>
      <% else %>
        <% if @profile.followers.any?{|follower| follower.id == current_user.id} %>
          <%= button_to "Unfollow",  unfollow_profiles_path, class: "inline-flex justify-center items-center px-5 py-2 rounded-full border ring-4 focus:ring-sky-50 ring-transparent hover:ring-sky-50 hover:border-gray-300" if current_user %>
        <% else %>
          <%= button_to "Follow",  follow_profiles_path, class: "inline-flex justify-center items-center px-5 py-2 rounded-full border ring-4 focus:ring-sky-50 ring-transparent hover:ring-sky-50 hover:border-gray-300" if current_user %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="mt-10 -mx-6">
    <% @profile.tweets.each do |tweet| %>
      <%= render partial: "tweets/#{tweet.tweet_type}", locals: { tweet: tweet } %>
    <% end %>
  </div>
</div>